version: '3.8'

services:
  web:
    build: .
    container_name: flask-monitoring
    expose:
      - "5000"  # ใช้ expose แทน ports เพราะ nginx เป็นตัวรับ request จริง
    volumes:
      - ./instance:/app/instance
      - ./app/static/uploads:/app/app/static/uploads
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/app/static
    depends_on:
      - web
    restart: always