"""Fix backref name conflict2

Revision ID: 203d6602e4a6
Revises: aaf32dbf8f5c
Create Date: 2025-01-13 15:26:26.790749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203d6602e4a6'
down_revision = 'aaf32dbf8f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('force_data_history', schema=None) as batch_op:
        batch_op.alter_column('remark',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('force_data_history', schema=None) as batch_op:
        batch_op.alter_column('remark',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
