"""delete username thanapoom to User table

Revision ID: 308be1898e38
Revises: bb65bec0a347
Create Date: 2024-12-19 15:35:09.107660

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '308be1898e38'
down_revision = 'bb65bec0a347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ลบผู้ใช้ที่มี username = 'thanapoom'
    op.execute("DELETE FROM User WHERE username = 'thanapoom'")
    op.execute("DELETE FROM User WHERE username = 'ThanapoomS'")
    op.execute("DELETE FROM User WHERE username = 'thanapoomss'")
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.alter_column('create_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
