"""add table knowledge

Revision ID: 47968410a3d7
Revises: 4cfec45bcf8f
Create Date: 2025-01-24 19:35:49.077546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47968410a3d7'
down_revision = '4cfec45bcf8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base',
    sa.Column('number', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('device_type', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('create_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_base')
    # ### end Alembic commands ###
