"""Add red_module, white_module, yellow_module

Revision ID: 4cfec45bcf8f
Revises: 203d6602e4a6
Create Date: 2025-01-21 21:34:11.762477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cfec45bcf8f'
down_revision = '203d6602e4a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('old_red_module', sa.String(length=100), nullable=True),
    sa.Column('new_red_module', sa.String(length=100), nullable=True),
    sa.Column('old_white_module', sa.String(length=100), nullable=True),
    sa.Column('new_white_module', sa.String(length=100), nullable=True),
    sa.Column('old_yellow_module', sa.String(length=100), nullable=True),
    sa.Column('new_yellow_module', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['device_name.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_name', schema=None) as batch_op:
        batch_op.add_column(sa.Column('red_module', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('white_module', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('yellow_module', sa.String(length=50), nullable=True))

    with op.batch_alter_table('force_data_history', schema=None) as batch_op:
        batch_op.alter_column('plus_before',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('force_data_history', schema=None) as batch_op:
        batch_op.alter_column('plus_before',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('device_name', schema=None) as batch_op:
        batch_op.drop_column('yellow_module')
        batch_op.drop_column('white_module')
        batch_op.drop_column('red_module')

    op.drop_table('module_history')
    # ### end Alembic commands ###
