"""Change Plus_Before to Integer in ForceDataHistory

Revision ID: 71377a3fa4d9
Revises: f242573750fb
Create Date: 2025-01-13 12:08:35.957961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71377a3fa4d9'
down_revision = 'f242573750fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('force_data_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('Plus_Before', sa.Integer(), nullable=False),
    sa.Column('Minus_Before', sa.Integer(), nullable=False),
    sa.Column('Plus_After', sa.Integer(), nullable=True),
    sa.Column('Minus_After', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['device_name.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_name', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('mac_address', sa.String(length=17), nullable=True))
        batch_op.add_column(sa.Column('channel', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('device_role', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('force_data', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vac_white', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('current_white', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vac_red', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('current_red', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vac_yellow', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('current_yellow', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('f1_f2', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_name', schema=None) as batch_op:
        batch_op.drop_column('f1_f2')
        batch_op.drop_column('current_yellow')
        batch_op.drop_column('vac_yellow')
        batch_op.drop_column('current_red')
        batch_op.drop_column('vac_red')
        batch_op.drop_column('current_white')
        batch_op.drop_column('vac_white')
        batch_op.drop_column('force_data')
        batch_op.drop_column('device_role')
        batch_op.drop_column('channel')
        batch_op.drop_column('mac_address')
        batch_op.drop_column('ip_address')

    op.drop_table('force_data_history')
    # ### end Alembic commands ###
