"""remove column action

Revision ID: bb65bec0a347
Revises: 430d293e659a
Create Date: 2024-12-18 23:02:42.186987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb65bec0a347'
down_revision = '430d293e659a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     # สร้างตารางใหม่ที่ไม่มีคอลัมน์ 'action'
    op.create_table(
        'work_new',
        sa.Column('number', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('create_date', sa.DateTime(), nullable=False, default=sa.func.now()),  # วันที่และเวลา สร้างอัตโนมัติ
        sa.Column('work_order', sa.String(50), nullable=False),
        sa.Column('line_id', sa.Integer, sa.ForeignKey('line.id'), nullable=True),
        sa.Column('location_id', sa.Integer, sa.ForeignKey('location.id'), nullable=True),
        sa.Column('device_type_id', sa.Integer, sa.ForeignKey('device_type.id'), nullable=True),
        sa.Column('device_name_id', sa.Integer, sa.ForeignKey('device_name.id'), nullable=True),
        sa.Column('description', sa.Text, nullable=False),
        sa.Column('report_by', sa.String(50), nullable=False),
        sa.Column('status', sa.String(20), nullable=False, default="open"),
        sa.Column('link', sa.String(255), nullable=True),
    )

    # คัดลอกข้อมูลจากตาราง 'work' ไปยังตาราง 'work_new'
    op.execute('''
        INSERT INTO work_new (number, create_date, work_order, line_id, location_id, device_type_id,
                              device_name_id, description, report_by, status, link)
        SELECT number, create_date, work_order, line_id, location_id, device_type_id, device_name_id,
               description, report_by, status, link
        FROM work
    ''')

    # ลบตาราง 'work' เดิม
    op.drop_table('work')

    # เปลี่ยนชื่อตาราง 'work_new' เป็น 'work'
    op.rename_table('work_new', 'work')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.TEXT(), nullable=True))
        batch_op.alter_column('create_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
