"""Add image_url column to Comment model

Revision ID: f242573750fb
Revises: 6140bfebe6b1
Create Date: 2024-12-26 11:01:30.970806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f242573750fb'
down_revision = '6140bfebe6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('pdf_url')

    # ### end Alembic commands ###
