"""Drop column bound and inandout from table serial

Revision ID: 0882dca297c0
Revises: 85a1a84bc240
Create Date: 2024-12-23 19:07:49.352103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0882dca297c0'
down_revision = '85a1a84bc240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('serial_number_history', schema=None) as batch_op:
        batch_op.drop_column('bound')
        batch_op.drop_column('inandout')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serial_number_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inandout', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('bound', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('device_name', schema=None) as batch_op:
        batch_op.alter_column('bound',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
