"""add column inandout to table devicename

Revision ID: 6140bfebe6b1
Revises: 0882dca297c0
Create Date: 2024-12-23 19:13:11.162164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6140bfebe6b1'
down_revision = '0882dca297c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_name', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inandout', sa.String(length=100), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_name', schema=None) as batch_op:
        batch_op.drop_column('inandout')

    # ### end Alembic commands ###
